// includes
const mongoose = require("mongoose");
const ObjectId = mongoose.Types.ObjectId;
const sanitize = require("mongo-sanitize");
const axios = require("axios");
const zlib = require("zlib");
// const sharp = require("sharp");
// const im = require("imagemagick-native");
const FormData = require("form-data"); // Ensure form-data is installed

// Models
const ServiceRequestModel = require("../../models/ServiceRequests");
const ComplaintTypesModel = require("../../models/ComplaintTypes");
// helper functions
const systemLogsHelper = require("../../helpers/system-logs");
const {
  sendResponse,
  checkKeysExist,
  updateLanguageContent,
  getModuleNameFromLanguage,
  getResponseMsgsFromLanguage,
  authenticateLoginCRM,
  getComplaintSetup,
  createComplaintRequestInCRM,
  getAllComplaintsFromCRM,
  createRequestFormInCRM,
  getAllRequestFormsFromCRM,
  getPolicyDetailsByPolicyNo,
  authenticate,
} = require("../../helpers/utils");

// module name
// const moduleName = 'Products'
// var lang= "english"
let moduleName;
let responseMsgs;
var lang = "english";

module.exports = {
  create,
  getAll,
  //   getById,
};

async function create(request, response) {
  lang = request.header("lang") ? request.header("lang") : "english";
  moduleName = await getModuleNameFromLanguage(lang, "ComplaintController");
  responseMsgs = await getResponseMsgsFromLanguage(lang, "ComplaintController");

  try {
    const { membershipNo, complaintTypeId, comment } = request.body;

    // ✅ Step 1: Validate required fields
    // const missingKeys = await checkKeysExist(request.body, [
    //   "membershipNo",
    //   "complaintTypeId",
    // ]);
    // if (missingKeys) {
    //   return sendResponse(response, moduleName, 422, 0, missingKeys);
    // }

    const policyNo = extractSerialNumber(membershipNo);
    if (!policyNo) {
      return sendResponse(
        response,
        moduleName,
        422,
        0,
        responseMsgs.inValidPolicyNoFormat ||
          "Invalid membership number format."
      );
    }

    let auth = await authenticate();
    // console.log('this is the auth response----',auth)

    if (auth) {
      let policy = await getPolicyDetailsByPolicyNo(
        request.user.cnic,
        policyNo,
        auth
      );
      // console.log('this is the response----',policy)

      if (policy && policy.Policies.length && policy.Policies.length > 0) {
        // Preparing dynamic data
        console.log("Policy Fetched =>>", policy.Policies[0]);

        // fetching complaint types data from DB
        let complaintType = await ComplaintTypesModel.findOne({
          _id: sanitize(complaintTypeId),
          status: "active",
        });

        if (!complaintType) {
          return sendResponse(
            response,
            moduleName,
            422,
            0,
            responseMsgs.complaintTypeNotFound
            // "Complaint Type Not found"
          );
        }

        // Get These Items from Policy cnic, channel, plan, PartnerName, FullName, PhoneNumber, Email
        console.log("Policy Data Found =>>", {
          MembershipNo: membershipNo,
          PolicyNo: policyNo,
          Comment: comment,
          ComplaintTypeId: complaintTypeId,
          Department: complaintType?.department?.id,
          ComplaintType: complaintType?.complaintType?.id,
          Cnic: policy?.Policies[0]?.OwnerInfo?.CNIC,
          FullName: policy?.Policies[0]?.OwnerInfo?.FullName,
          Mobile: policy?.Policies[0]?.OwnerInfo?.Mobile,
          Email: policy?.Policies[0]?.OwnerInfo?.Email,
          FullAddress: policy?.Policies[0]?.OwnerInfo?.FullAddress,
          Channel: policy?.Policies[0]?.Channel,
          Plan: policy?.Policies[0]?.Plan,
          PartnerName: policy?.Policies[0]?.PartnerName,
        });

        const policyData = {
          MembershipNo: membershipNo,
          PolicyNo: policyNo,
          Comment: comment,
          ComplaintTypeId: complaintTypeId,
          Department: complaintType?.department?.id,
          ComplaintType: complaintType?.complaintType?.id,
          Cnic: policy?.Policies[0]?.OwnerInfo?.CNIC,
          FullName: policy?.Policies[0]?.OwnerInfo?.FullName,
          Mobile: policy?.Policies[0]?.OwnerInfo?.Mobile,
          Email: policy?.Policies[0]?.OwnerInfo?.Email,
          FullAddress: policy?.Policies[0]?.OwnerInfo?.FullAddress,
          Channel: policy?.Policies[0]?.Channel,
          Plan: policy?.Policies[0]?.Plan,
          PartnerName: policy?.Policies[0]?.PartnerName,
        };

        // ✅ Call setup logic here
        const complaintSetupParams = await getComplaintSetupLogic(policyData);
        console.log("Complaint Setup Parameters =>>", complaintSetupParams);

        // Logic start to Prepare Third Party payload for Form-Data
        const files = request.files; // populated by multer

        // // ✅ Step 2: Prepare form-data for third-party
        const formData = new FormData();

        formData.append("Type", complaintSetupParams?.Type || "");
        formData.append("MembershipNumber", membershipNo);
        formData.append("CNIC", policy?.Policies[0]?.OwnerInfo?.CNIC || "");
        formData.append("ProductId", complaintSetupParams?.ProductId || "");
        formData.append("DepartmentId", complaintType?.department?.id || "");
        // formData.append("DepartmentId", "1" || "");
        formData.append(
          "ComplaintTypeId",
          complaintType?.complaintType?.id || ""
          // "23" || ""
        );
        formData.append(
          "ComplaintSourceId",
          complaintSetupParams?.ComplaintSourceId || ""
        );
        formData.append(
          "Address",
          policy?.Policies[0]?.OwnerInfo?.FullAddress || ""
        );
        formData.append("BankName", complaintSetupParams?.BankName || "");
        formData.append(
          "ParticipantName",
          policy?.Policies[0]?.OwnerInfo?.FullName || ""
        );
        formData.append(
          "CustomerMobileNumber",
          policy?.Policies[0]?.OwnerInfo?.Mobile || ""
        );
        formData.append("Email", policy?.Policies[0]?.OwnerInfo?.Email || "");
        formData.append("ComplaintNote", comment);

        // if (files && files.length > 0) {
        //   files.forEach((file, index) => {
        //     formData.append("files[]", file.buffer, file.originalname);
        //   });
        // }
        if (files && files.length > 0) {
          const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5 MB

          for (const file of files) {
            if (file.size > MAX_FILE_SIZE) {
              return sendResponse(
                response,
                moduleName,
                422,
                0,
                `File "${file.originalname}" is too large. Please try again with files under 5MB.`
                // "Complaint not created."
              );
            }
          }

          files.forEach((file) => {
            formData.append("files[]", file.buffer, file.originalname);
          });
        }

        // ✅ Step 3: Send to third-party endpoint
        if (formData) {
          console.log("==== Final Form Data ====", formData);
          if (complaintSetupParams?.Auth) {
            const complaintRequestSent = await createComplaintRequestInCRM(
              complaintSetupParams?.Auth,
              formData
            );
            console.log(
              "Complaint Creation Response From 5th pillar API",
              complaintRequestSent
            );

            if (
              complaintRequestSent &&
              complaintRequestSent?.StatusCode === "200"
            ) {
              return sendResponse(
                response,
                moduleName,
                200,
                1,
                responseMsgs.complaintCreated ||
                  "Complaint successfully created.",
                complaintRequestSent?.Data
              );
            } else {
              return sendResponse(
                response,
                moduleName,
                422,
                0,
                responseMsgs.complaintNotCreated
                // "Complaint not created."
              );
            }
          }
        }
      }
    }

    return sendResponse(response, moduleName, 422, 0, responseMsgs.authFailed);
  } catch (error) {
    console.error("--- Forwarding Error ---", error.message);
    return sendResponse(
      response,
      moduleName,
      500,
      0,
      responseMsgs.error_500 || "Something went wrong while sending data."
    );
  }
}

/** Get All Complaint Requests **/
async function getAll(request, response) {
  lang = request.header("lang") ? request.header("lang") : lang;
  moduleName = await getModuleNameFromLanguage(lang, "ComplaintController");
  responseMsgs = await getResponseMsgsFromLanguage(lang, "ComplaintController");
  try {
    // return sendResponse(
    //   response,
    //   moduleName,
    //   200,
    //   1,
    //   responseMsgs.complaintsFetched,
    //   {
    //     complaints: [
    //       {
    //         complaint_id: 18,
    //         policy_num: "12345678910",
    //         response_number: "",
    //         daily_counter: 1,
    //         complaint_num: "CTID250530001",
    //         customer_name: "Zohaib",
    //         cnic: "4210177399897",
    //         agent_id: 1,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "13",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2 Working Days",
    //         mode: "1",
    //         type: "individual",
    //         progress: 0,
    //         file_counter: 0,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 16:43:30",
    //         end_date: "2025-06-03 16:43:30",
    //         forward_date: "2025-05-30 16:43:30",
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Super Admin",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 9,
    //         policy_num: "12345678",
    //         response_number: "",
    //         daily_counter: 1,
    //         complaint_num: "CTBI250530001",
    //         customer_name: "Zohaib",
    //         cnic: "4210177399897",
    //         agent_id: 1,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "12",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2 Working Days",
    //         mode: "1",
    //         type: "bancaIndividual",
    //         progress: 0,
    //         file_counter: 0,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 16:41:04",
    //         end_date: "2025-06-03 16:41:04",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Super Admin",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 10,
    //         policy_num: "12345678",
    //         response_number: "",
    //         daily_counter: 2,
    //         complaint_num: "CTBI250530002",
    //         customer_name: "Zohaib",
    //         cnic: "4210177399897",
    //         agent_id: 1,
    //         group_id: 35,
    //         user_id: "238",
    //         product_id: "13",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 2,
    //         channel: "2",
    //         tat: "2 Working Days",
    //         mode: "1",
    //         type: "bancaIndividual",
    //         progress: 50,
    //         file_counter: 0,
    //         comments: "test",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 16:52:03",
    //         end_date: "2025-06-03 16:52:03",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Super Admin",
    //         ComplaintType: "Delay in response",
    //         Source: "Call",
    //         AssignedTo: "Muhammad  Talha Javed",
    //         depart: "Participant services Department",
    //         cmpStatus: "in progress",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 11,
    //         policy_num: "12345678",
    //         response_number: "",
    //         daily_counter: 3,
    //         complaint_num: "CTBI250530003",
    //         customer_name: "Zohaib",
    //         cnic: "4210177399897",
    //         agent_id: 238,
    //         group_id: 35,
    //         user_id: "238",
    //         product_id: "13",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 3,
    //         channel: "1",
    //         tat: "2 Working Days",
    //         mode: "1",
    //         type: "bancaIndividual",
    //         progress: 100,
    //         file_counter: 0,
    //         comments: "Done",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 17:10:41",
    //         end_date: "2025-06-03 17:10:41",
    //         forward_date: null,
    //         close_date: "2025-05-30 17:11:12",
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Muhammad  Talha Javed",
    //         ComplaintType: "Delay in response",
    //         Source: "Email",
    //         AssignedTo: "Muhammad  Talha Javed",
    //         depart: "Participant services Department",
    //         cmpStatus: "closed",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 16,
    //         policy_num: "00",
    //         response_number: "03464389272",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250521003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 1,
    //         user_id: "220",
    //         product_id: "1",
    //         complaint_depart: 1,
    //         complaint_type_id: 23,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "5",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-21 17:55:33",
    //         end_date: "1970-01-01 17:55:33",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: null,
    //         ReleasedBy: "Api User",
    //         ComplaintType: null,
    //         Source: "Mobile App",
    //         AssignedTo: "Talha Hussain",
    //         depart: null,
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521003/CTBB250521003_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521003_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521003/CTBB250521003_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521003_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 17,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 4,
    //         complaint_num: "CTBB250521004",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 1,
    //         user_id: "220",
    //         product_id: "1",
    //         complaint_depart: 1,
    //         complaint_type_id: 23,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "5",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-21 18:01:44",
    //         end_date: "1970-01-01 18:01:44",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: null,
    //         ReleasedBy: "Api User",
    //         ComplaintType: null,
    //         Source: "Mobile App",
    //         AssignedTo: "Talha Hussain",
    //         depart: null,
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521004/CTBB250521004_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521004_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521004/CTBB250521004_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521004_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 18,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 5,
    //         complaint_num: "CTBB250521005",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 1,
    //         user_id: "220",
    //         product_id: "1",
    //         complaint_depart: 1,
    //         complaint_type_id: 23,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "5",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-21 18:08:05",
    //         end_date: "1970-01-01 18:08:05",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: null,
    //         ReleasedBy: "Api User",
    //         ComplaintType: null,
    //         Source: "Mobile App",
    //         AssignedTo: "Talha Hussain",
    //         depart: null,
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521005/CTBB250521005_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521005_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250521005/CTBB250521005_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250521005_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 20,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 2,
    //         complaint_num: "CTBB250522002",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 1,
    //         user_id: "220",
    //         product_id: "1",
    //         complaint_depart: 1,
    //         complaint_type_id: 23,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "5",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-22 09:46:42",
    //         end_date: "1970-01-01 09:46:42",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: null,
    //         ReleasedBy: "Api User",
    //         ComplaintType: null,
    //         Source: "Mobile App",
    //         AssignedTo: "Talha Hussain",
    //         depart: null,
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 21,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250522003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 1,
    //         user_id: "220",
    //         product_id: "1",
    //         complaint_depart: 1,
    //         complaint_type_id: 23,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "5",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-22 09:47:19",
    //         end_date: "1970-01-01 09:47:19",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: null,
    //         ReleasedBy: "Api User",
    //         ComplaintType: null,
    //         Source: "Mobile App",
    //         AssignedTo: "Talha Hussain",
    //         depart: null,
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522003/CTBB250522003_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522003_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522003/CTBB250522003_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522003_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 24,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 6,
    //         complaint_num: "CTBB250522006",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-22 15:45:31",
    //         end_date: "2025-05-26 15:45:31",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-29 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-26 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522006/CTBB250522006_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522006_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522006/CTBB250522006_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522006_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 25,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 7,
    //         complaint_num: "CTBB250522007",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-22 16:35:52",
    //         end_date: "2025-05-26 16:35:52",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-29 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-26 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522007/CTBB250522007_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522007_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250522007/CTBB250522007_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250522007_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 26,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 1,
    //         complaint_num: "CTBB250523001",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 12:58:31",
    //         end_date: "2025-05-27 12:58:31",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 27,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 2,
    //         complaint_num: "CTBB250523002",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 13:37:37",
    //         end_date: "2025-05-27 13:37:37",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 28,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250523003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 13:39:18",
    //         end_date: "2025-05-27 13:39:18",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 29,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 4,
    //         complaint_num: "CTBB250523004",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 13:53:10",
    //         end_date: "2025-05-27 13:53:10",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 30,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 5,
    //         complaint_num: "CTBB250523005",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 13:55:41",
    //         end_date: "2025-05-27 13:55:41",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 31,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 6,
    //         complaint_num: "CTBB250523006",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 13:56:27",
    //         end_date: "2025-05-27 13:56:27",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 32,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 7,
    //         complaint_num: "CTBB250523007",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 14:06:50",
    //         end_date: "2025-05-27 14:06:50",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 33,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 8,
    //         complaint_num: "CTBB250523008",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 15:50:42",
    //         end_date: "2025-05-27 15:50:42",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 34,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 9,
    //         complaint_num: "CTBB250523009",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 15:53:46",
    //         end_date: "2025-05-27 15:53:46",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 35,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 10,
    //         complaint_num: "CTBB250523010",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 16:13:09",
    //         end_date: "2025-05-27 16:13:09",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 41,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 16,
    //         complaint_num: "CTBB250523016",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:30:09",
    //         end_date: "2025-05-27 17:30:09",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 42,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 17,
    //         complaint_num: "CTBB250523017",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:30:55",
    //         end_date: "2025-05-27 17:30:55",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 43,
    //         policy_num: "00",
    //         response_number: "03464389272",
    //         daily_counter: 18,
    //         complaint_num: "CTBB250523018",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:33:46",
    //         end_date: "2025-05-27 17:33:46",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 44,
    //         policy_num: "00",
    //         response_number: "03464389272",
    //         daily_counter: 19,
    //         complaint_num: "CTBB250523019",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:34:14",
    //         end_date: "2025-05-27 17:34:14",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 45,
    //         policy_num: "00",
    //         response_number: "03464389272",
    //         daily_counter: 20,
    //         complaint_num: "CTBB250523020",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:34:31",
    //         end_date: "2025-05-27 17:34:31",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250523020/CTBB250523020_file-1738152231846.png",
    //             FileType: "complain",
    //             FileName: "CTBB250523020_file-1738152231846.png",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250523020/CTBB250523020_file-1745872093425.png",
    //             FileType: "complain",
    //             FileName: "CTBB250523020_file-1745872093425.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 46,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 21,
    //         complaint_num: "CTBB250523021",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-23 17:38:26",
    //         end_date: "2025-05-27 17:38:26",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: "2025-05-30 06:00:01",
    //         escalation_2: null,
    //         escalation_3: "2025-05-27 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250523021/CTBB250523021_cropped_1748003639804.png",
    //             FileType: "complain",
    //             FileName: "CTBB250523021_cropped_1748003639804.png",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 47,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 1,
    //         complaint_num: "CTBB250526001",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-26 05:24:49",
    //         end_date: "2025-05-28 05:24:49",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-28 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526001/CTBB250526001_image_r90apr.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526001_image_r90apr.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 48,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 2,
    //         complaint_num: "CTBB250526002",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-26 05:38:22",
    //         end_date: "2025-05-28 05:38:22",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-28 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526002/CTBB250526002_image_4sk31s.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526002_image_4sk31s.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 49,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250526003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-26 05:39:52",
    //         end_date: "2025-05-28 05:39:52",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-28 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526003/CTBB250526003_DocSupport.pdf",
    //             FileType: "complain",
    //             FileName: "CTBB250526003_DocSupport.pdf",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526003/CTBB250526003_image_fk3enh.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526003_image_fk3enh.jpg",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526003/CTBB250526003_image_j9qevw.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526003_image_j9qevw.jpg",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526003/CTBB250526003_image_q1b7fu.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526003_image_q1b7fu.jpg",
    //           },
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526003/CTBB250526003_image_yukr26.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526003_image_yukr26.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 50,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 4,
    //         complaint_num: "CTBB250526004",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-26 05:42:40",
    //         end_date: "2025-05-28 05:42:40",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-28 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250526004/CTBB250526004_image_0ifvhl.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250526004_image_0ifvhl.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 51,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 5,
    //         complaint_num: "CTBB250526005",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-26 11:30:53",
    //         end_date: "2025-05-28 11:30:53",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-28 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 52,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 1,
    //         complaint_num: "CTBB250527001",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-27 02:05:03",
    //         end_date: "2025-05-29 02:05:03",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: "2025-05-29 06:00:01",
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250527001/CTBB250527001_DocSupport.pdf",
    //             FileType: "complain",
    //             FileName: "CTBB250527001_DocSupport.pdf",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 57,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250529003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 17:06:38",
    //         end_date: "2025-06-02 17:06:38",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250529003/CTBB250529003_cropped_1748520390879.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250529003_cropped_1748520390879.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 58,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 4,
    //         complaint_num: "CTBB250529004",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 17:07:31",
    //         end_date: "2025-06-02 17:07:31",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 59,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 5,
    //         complaint_num: "CTBB250529005",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 17:07:39",
    //         end_date: "2025-06-02 17:07:39",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250529005/CTBB250529005_cropped_1748520437896.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250529005_cropped_1748520437896.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 60,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 6,
    //         complaint_num: "CTBB250529006",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 17:09:03",
    //         end_date: "2025-06-02 17:09:03",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 61,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 7,
    //         complaint_num: "CTBB250529007",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 17:09:31",
    //         end_date: "2025-06-02 17:09:31",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 62,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 8,
    //         complaint_num: "CTBB250529008",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-29 18:02:08",
    //         end_date: "2025-06-02 18:02:08",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [
    //           {
    //             file: "https://uat-crm.5thpillartakaful.com//Fifthpillar-CRM/uploads_eform_complaint/complaint_attachment/CTBB250529008/CTBB250529008_image_skgmz9.jpg",
    //             FileType: "complain",
    //             FileName: "CTBB250529008_image_skgmz9.jpg",
    //           },
    //         ],
    //       },
    //       {
    //         complaint_id: 63,
    //         policy_num: "00",
    //         response_number: "03362255584",
    //         daily_counter: 1,
    //         complaint_num: "CTBB250530001",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "232",
    //         product_id: "1",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "9",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 13:42:44",
    //         end_date: "2025-06-03 13:42:44",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Mobile App",
    //         AssignedTo: "Nainta Nazim",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //       {
    //         complaint_id: 65,
    //         policy_num: "00",
    //         response_number: "03464389272",
    //         daily_counter: 3,
    //         complaint_num: "CTBB250530003",
    //         customer_name: "0",
    //         cnic: "4210177399897",
    //         agent_id: 253,
    //         group_id: 35,
    //         user_id: "238",
    //         product_id: "3",
    //         complaint_depart: 35,
    //         complaint_type_id: 2,
    //         priority_id: "High",
    //         status_id: 1,
    //         channel: "3",
    //         tat: "2",
    //         mode: "1",
    //         type: "bancaBank",
    //         progress: 0,
    //         file_counter: null,
    //         comments: "",
    //         comments_progress: null,
    //         comments_verified: null,
    //         create_date: "2025-05-30 16:58:47",
    //         end_date: "2025-06-03 16:58:47",
    //         forward_date: null,
    //         close_date: null,
    //         escalation_1: null,
    //         escalation_2: null,
    //         escalation_3: null,
    //         escalation_4: null,
    //         category: "Non Financial",
    //         ReleasedBy: "Api User",
    //         ComplaintType: "Delay in response",
    //         Source: "Letter",
    //         AssignedTo: "Muhammad  Talha Javed",
    //         depart: "Participant services Department",
    //         cmpStatus: "initiated",
    //         files: [],
    //       },
    //     ],
    //   }
    // );

    const userCnic = request?.user?.cnic?.replace(/-/g, "");

    if (!userCnic) {
      return sendResponse(
        response,
        moduleName,
        400,
        1,
        responseMsgs.customerNotFound
      );
    }
    const [auth] = await Promise.all([authenticateLoginCRM()]);

    if (!auth) {
      return sendResponse(
        response,
        moduleName,
        200,
        1,
        responseMsgs.authFailed
      );
    }

    // Fetch complaints from CRM
    const getAllComplaints = await getAllComplaintsFromCRM(auth, userCnic);
    console.log("Complaints Response From 5th Pillar API:", getAllComplaints);

    if (
      getAllComplaints?.StatusCode !== "200" ||
      !getAllComplaints?.Data?.length
    ) {
      return sendResponse(
        response,
        moduleName,
        200,
        1,
        responseMsgs.recordNotFound
      );
    }

    // Process and sort the response data
    // const collectedComplaintsData = getAllComplaints.Data.map((element) => {
    //   const normalizedStatus = element.cmpStatus
    //     ?.toLowerCase()
    //     .replace(/\s+/g, "");

    //   element.cmpStatus = ["inprogress", "onhold"].includes(normalizedStatus)
    //     ? "In Progress"
    //     : ["closed", "closedasunresolved", "invalid"].includes(normalizedStatus)
    //     ? "Close"
    //     : element.cmpStatus;

    //   return element;
    // }).sort((a, b) => new Date(b.create_date) - new Date(a.create_date));

    const collectedComplaintsData = await Promise.all(
      getAllComplaints.Data.map(async (item) => {
        const normalizedStatus = item.cmpStatus
          ?.toLowerCase()
          .replace(/\s+/g, "");

        item.cmpStatus = ["inprogress", "onhold"].includes(normalizedStatus)
          ? "In Progress"
          : ["closed", "closedasunresolved", "invalid"].includes(
              normalizedStatus
            )
          ? "Closed"
          : item.cmpStatus;

        // Ensure both are numbers
        const complaintDepartId = Number(item.complaint_depart);
        const complaintTypeId = Number(item.complaint_type_id);

        // Fetch complaint type title
        const complaintType = await ComplaintTypesModel.findOne({
          "department.id": complaintDepartId,
          "complaintType.id": complaintTypeId,
          status: "active",
        });

        item.ComplaintType = complaintType?.title?.english || "N/A";

        return item;
      })
    );

    // Sort by create_date descending
    collectedComplaintsData.sort(
      (a, b) => new Date(b.create_date) - new Date(a.create_date)
    );

    return sendResponse(
      response,
      moduleName,
      200,
      1,
      responseMsgs.complaintsFetched,
      {
        complaints: collectedComplaintsData,
      }
    );
  } catch (error) {
    console.error("--- Get All Complaints API Error ---", error);
    return sendResponse(
      response,
      moduleName,
      500,
      0,
      responseMsgs.error_500
      //   "Something went wrong, please try again later."
    );
  }
}

// /** Get Service Request by Id **/
// async function getById(request, response) {
//   let params = request.params;
//   lang = request.header("lang") ? request.header("lang") : lang;
//   moduleName = await getModuleNameFromLanguage(
//     lang,
//     "ComplaintController"
//   );
//   responseMsgs = await getResponseMsgsFromLanguage(
//     lang,
//     "ComplaintController"
//   );

//   try {
//     /** set model to fetch **/
//     const model = await ServiceRequestModel;

//     $aggregate = [
//       {
//         $lookup: {
//           from: "systemUsers",
//           localField: "createdBy",
//           foreignField: "_id",
//           as: "createdByDetails",
//         },
//       },
//       {
//         $unwind: {
//           path: "$createdByDetails",
//           preserveNullAndEmptyArrays: true,
//         },
//       },
//     ];

//     $aggregate.push({
//       $match: {
//         _id: new ObjectId(params.serviceRequestId),
//       },
//     });

//     let $project = {
//       _id: "$_id",
//       title: "$title." + lang,
//       type: "$type",
//       category: "$category",
//       subCategory: "$subCategory",
//       ISM: "$ISM",
//       tags: "$tags." + lang,
//       description: "$description." + lang,
//       content: "$content." + lang,
//       isZakatDoc: "$isZakatDoc",
//       status: "$status",
//       createdBy: "$createdByDetails.fullName",
//       files: "$files." + lang,
//       createdAt: "$createdAt",
//     };

//     let data = await model.aggregate([$aggregate]).project($project).exec();
//     let responseData = null;
//     if (data && data.length && data.length > 0) {
//       responseData = data[0];
//     }
//     //create system logs
//     let systemLogsData = {
//       userId: request.user._id,
//       userIp: request.ip,
//       roleId: request.user.roleId,
//       module: moduleName,
//       action: "getById",
//       data: responseData,
//     };
//     let systemLogs = await systemLogsHelper.composeSystemLogs(systemLogsData);

//     return sendResponse(
//       response,
//       moduleName,
//       200,
//       1,
//       responseMsgs.serviceRequestFetched,
//       // "Service Request fetched",
//       responseData
//     );
//   } catch (error) {
//     console.log("--- getById API error ---", error);
//     return sendResponse(
//       response,
//       moduleName,
//       500,
//       0,
//       responseMsgs.error_500
//       // "Something went wrong, please try again later."
//     );
//   }
// }

async function getComplaintSetupLogic(policyData) {
  try {
    const auth = await authenticateLoginCRM();
    if (auth) {
      const complaintSetupData = await getComplaintSetup(auth);
      console.log("complaint Setup API Call ==> ", complaintSetupData);

      if (complaintSetupData && complaintSetupData?.StatusCode === "200") {
        const setupData = complaintSetupData?.Data;

        // 1. Type and BankName
        let type,
          bankName = "";
        console.log("Channel", policyData.Channel);
        if (policyData.Channel === "Bancassurance") {
          console.log("Channel is Bancassurance");
          type =
            setupData?.ComplaintCategory?.find(
              (item) => item === "bancaIndividual"
            ) || setupData?.ComplaintCategory?.[0];

          bankName = policyData.PartnerName || "";
        } else {
          console.log("Channel is not Bancassurance");
          type =
            setupData?.ComplaintCategory?.find(
              (item) => item === "individual"
            ) || setupData?.ComplaintCategory?.[0];
        }

        // 2. ProductId
        const product = setupData?.Product?.find(
          (item) => item?.fullname === policyData.Plan
        );
        const productId = product?.id || setupData?.Product?.[0]?.id;

        // 3. ComplaintSourceId (Mobile App)
        const complaintSourceId =
          setupData?.ComplaintSource?.find(
            (item) => item?.fullname === "Mobile App"
          )?.id || setupData?.ComplaintSource?.[0]?.id;

        // Final Return Object
        return {
          Auth: auth,
          Type: type,
          BankName: bankName,
          ProductId: productId,
          ComplaintSourceId: complaintSourceId,
        };
      }
    }
  } catch (error) {
    console.error("--- Forwarding Error ---", error.message);
    return sendResponse(
      response,
      moduleName,
      500,
      0,
      responseMsgs.error_500 || "Something went wrong while sending data."
    );
  }
}

// function extractSerialNumber(membershipNo) {
//   if (!membershipNo || typeof membershipNo !== "string") return null;

//   // Match the number sequence before the dash (excluding prefix)
//   const match = membershipNo.match(/5PUL\d{4}(\d{9})-\d$/);

//   return match ? match[1] : null;
// }

function extractSerialNumber(membershipNo) {
  if (!membershipNo || typeof membershipNo !== "string") return null;

  const match = membershipNo.match(/(\d{9})-\d$/);

  return match ? match[1] : null;
}
